### ISSUE TITLE
Tar ASCII translation does not work

### ISSUE THREAD

**Issue by dgrunwald** [icsharpcode/SharpZipLib#27]
[SD-744](http://bugtracker.sharpdevelop.net/issue/ViewIssue.aspx?id=744), originally created on 4/2/2006 22:23:38 by John Reilly

I have met just a little prbl whith TAR.GZ files when I set the
asciiTranslate option on "true". When this option is set on false,
everything works great, but when it is on true, an IOException appears
:(

Here is the full error message :
__________________________________
Une exception non gérée du type 'System.IO.IOException' s'est produite
dans mscorlib.dll

Informations supplémentaires : Le processus ne peut pas accéder au
fichier "C:\Documents and Settings\Jeje\Mes documents\Visual Studio
Projects\TestXLAccess\bin\Debug\Test\batchs\purge.sh", car il est
en cours d'utilisation par un autre processus.
_______________________________________

I guess you prefer in English ;-)
__________________________________
A non handeled exception of  'System.IO.IOException' type has occured in
mscorlib.dll

Further information : The process cannot access to the file
"C:\Documents and Settings\Jeje\Mes documents\Visual Studio
Projects\TestXLAccess\bin\Debug\Test\batchs\purge.sh", because it
is being used by an other process
_______________________________________

So, I think SharpZipLib might create a new process to write into text
files but there is a colision with the main process which has created
the file or something like that.

If you have any idea about how this little bug could be resolved, I
would be glad to hear it :)

Thx again for your work.
Jerome

**Comment by piksel** [comment]
This should have been fixed by #326

**Comment by Numpsy** [comment]
was the translate option on extract actually fixed? I had a recollection that there was still an issue with it trying to read a file that it had locked for write, though I might be misremembering.

**Comment by piksel** [comment]
Well, both yes and no :3

It *was* fixed as it is no longer trying to open the file twice, so no exception.
But it's still checking if the *destionation* file is ASCII, which will never be true, so that part is still wrong (which simply means that we don't do any translation).
